routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CheckboxController;
use App\Http\Controllers\DepartmentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('companies', CompanyController::class);
Route::resource('departments', DepartmentController::class);
Route::resource('checkboxes', CheckboxController::class);

app/Models/Checkbox.php
<?php

namespace App\Models;

use App\Models\Checkbox;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Checkbox extends Model
{
    use HasFactory;
}

app/Http/Controllers/CheckboxController.php
<?php
namespace App\Http\Controllers;
use App\Models\Checkbox;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CheckboxController extends Controller
{
/**
* Display a listing of the resource.
*
* @return \Illuminate\Http\Response
*/
public function index(Request $request)
{
    // dd($request->first_name);
    $data = Checkbox::select('id','firstname','lastname','email','address','contactnumber','subjects','faculty');
    // for search
    if($request->search){
        $data->where('firstname','like','%'.$request->search.'%')
            ->orWhere('lastname','like','%'.$request->search.'%');
    }
       
    // for filter
    if($request->first_name){
        $data->where('firstname','like','%'.$request->first_name.'%');
    }
    if($request->last_name){
        $data->where('firstname','like','%'.$request->last_name.'%');
    }
    $checkboxes = $data->get();
    $search = $request->search;            
    $firstname = $request->first_name;            
    $lastname = $request->last_name;            
    return view('checkboxes.index',compact('checkboxes','search','firstname','lastname'));
}
/**
* Show the form for creating a new resource.
*
* @return \Illuminate\Http\Response
*/
public function create()
{
   
    return view('checkboxes.create');
}
/**
* Store a newly created resource in storage.
*
* @param  \Illuminate\Http\Request  $request
* @return \Illuminate\Http\Response
*/
public function store(Request $request)
{
// $request->validate([
// 'firstname' => 'required',
// 'lastname' => 'required',
// 'address' => 'required',
// 'email' => 'required',
// 'contactnumber' => 'required',
// 'faculty' => 'required',
// ]);
$checkbox = new Checkbox;
$checkbox->firstname = $request->firstname;
$checkbox->lastname = $request->lastname;
$checkbox->email = $request->email;
$checkbox->address = $request->address;
$checkbox->contactnumber = $request->contactnumber;
$checkbox->subjects = implode(',',$request->subjects);
$checkbox->faculty = $request->faculty;
$checkbox->save();
return redirect()->route('checkboxes.index')
->with('success','Checkbox has been created successfully.');
}
/**
* Display the specified resource.
*
* @param  \App\company  $company
* @return \Illuminate\Http\Response
*/
public function show(Checkbox $checkboxes)
{
return view('checkboxes.show',compact('checkbox'));
} 
/**
* Show the form for editing the specified resource.
*
* @param  \App\Company  $company
* @return \Illuminate\Http\Response
*/
public function edit($checkbox)
{
       
        
        // return view('checkboxes.edit',compact('checkbox'));
        return view('checkboxes.edit')->with('checkbox',Checkbox::find($checkbox));
}
/**
* Update the specified resource in storage.
*
* @param  \Illuminate\Http\Request  $request
* @param  \App\company  $company
* @return \Illuminate\Http\Response
*/
public function update(Request $request, $id)
{
$request->validate([
    'firstname' => 'required',
    'lastname' => 'required',
    'address' => 'required',
    'email' => 'required',
    'contactnumber' => 'required',
    'faculty' => 'required',
]);
$checkbox = Checkbox::find($id);
$checkbox->firstname = $request->firstname;
$checkbox->lastname = $request->lastname;
$checkbox->email = $request->email;
$checkbox->address = $request->address;
$checkbox->contactnumber = $request->contactnumber;
$checkbox->subjects = implode(',',$request->subjects);
$checkbox->faculty = $request->faculty;
$checkbox->save();
return redirect()->route('checkboxes.index')
->with('success','Checkbox Has Been updated successfully');
}
/**
* Remove the specified resource from storage.
*
* @param  \App\Company  $company
* @return \Illuminate\Http\Response
*/
public function destroy(Checkbox $checkbox)
{
    $checkbox->delete();
    return redirect()->route('checkboxes.index')
    ->with('success','checkbox has been deleted successfully');
}
}

resources/views/checkboxes/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Checkbox</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
<div class="container mt-2">
<div class="row">
<div class="col-lg-12 margin-tb">
<div class="pull-left mb-2">
<h2>Add Student</h2>
</div>
<div class="pull-right">
<a class="btn btn-primary" href="{{ route('checkboxes.index') }}"> Back</a>
</div>
</div>
</div>
@if(session('status'))
<div class="alert alert-success mb-1 mt-1">
{{ session('status') }}
</div>
@endif
<form action="{{ route('checkboxes.store') }}" method="POST" enctype="multipart/form-data">
@csrf
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>First Name:</strong>
<input type="text" name="firstname" class="form-control" placeholder="First Name">
@error('name')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Last Name:</strong>
<input type="text" name="lastname" class="form-control" placeholder="Last Name">
@error('name')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Email:</strong>
<input type="email" name="email" class="form-control" placeholder="Email">
@error('email')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Address:</strong>
<input type="text" name="address" class="form-control" placeholder="Address">
@error('address')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Contact Number:</strong>
<input type="text" name="contactnumber" class="form-control" placeholder="Contact Number">
@error('contactnumber')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Subjects:</strong>
<!-- <input type="checkbox" name="subjects" class="form-control" placeholder="Subjects"> -->

<label class="container">Maths
  <input type="checkbox" name="subjects[]" value="maths">
  <span class="checkmark"></span>
</label>

<label class="container">Science
  <input type="checkbox" name="subjects[]" value="science ">
  <span class="checkmark"></span>
</label>

<label class="container">Account
  <input type="checkbox" name="subjects[]" value="account">
  <span class="checkmark"></span>
</label>

<label class="container">Business
  <input type="checkbox" name="subjects[]" value="business">
  <span class="checkmark"></span>
</label>

<label class="container">Law Study
  <input type="checkbox" name="subjects[]" value="law">
  <span class="checkmark"></span>
</label>

@error('subjects')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Faculty:</strong><br>
<!-- <input type="radio" name="faculty" class="form-control" placeholder="Faculty"> -->

  <input type="radio" id="science" name="faculty" value="science">
  <label for="science">SCIENCE</label><br>
  <input type="radio" id="management" name="faculty" value="management">
  <label for="management">MANAGEMENT</label><br>
  <input type="radio" id="law" name="faculty" value="law">
  <label for="law">LAW</label>
@error('faculty')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<button type="ok" class="btn btn-primary ml-3">OK</button>
</div>
</form>
</body>
</html>

resources/views/checkboxes/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Checkbox</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
<div class="container mt-2">
<div class="row">
<div class="col-lg-12 margin-tb">
<div class="pull-left">
<h2>Edit Entrance Form</h2>
</div>
<div class="pull-right">
<a class="btn btn-primary" href="{{ route('checkboxes.index') }}" enctype="multipart/form-data"> Back</a>
</div>
</div>
</div>
@if(session('status'))
<div class="alert alert-success mb-1 mt-1">
{{ session('status') }}
</div>
@endif
<form action="{{ route('checkboxes.update',$checkbox->id) }}" method="POST" enctype="multipart/form-data">
@csrf
@method('PUT')
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>First Name:</strong>
<input type="text" name="firstname" value="{{ $checkbox->firstname }}" class="form-control" placeholder="First Name">
@error('firstname')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Last Name:</strong>
<input type="text" name="lastname" value="{{ $checkbox->lastname }}" class="form-control" placeholder="Last Name">
@error('lastname')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Email:</strong>
<input type="email" name="email" class="form-control" placeholder="Email" value="{{ $checkbox->email }}">
@error('email')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Address:</strong>
<input type="text" name="address" value="{{ $checkbox->address }}" class="form-control" placeholder="Address">
@error('address')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Contact Number:</strong>
<input type="text" name="contactnumber" value="{{ $checkbox->contactnumber }}" class="form-control" placeholder="Contact Number">
@error('contactnumber')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Subjects:</strong>
@php
$subjects = explode(',',$checkbox->subjects);
@endphp 

<label class="container">Maths
  <input type="checkbox" name="subjects[]" value="maths"{{ in_array('maths',$subjects) ? 'checked' :'' }}>
  <span class="checkmark"></span>
</label>

<label class="container">Science
  <input type="checkbox" name="subjects[]" value="science" {{ in_array('science',$subjects) ? 'checked' :'' }}>
  <span class="checkmark"></span>
</label>

<label class="container">Account
  <input type="checkbox" name="subjects[]" value="account" {{ in_array('account',$subjects) ? 'checked' :'' }}>
  <span class="checkmark"></span>
</label>

<label class="container">Business
  <input type="checkbox" name="subjects[]" value="business" {{ in_array('business',$subjects) ? 'checked' :'' }}>
  <span class="checkmark"></span>
</label>

<label class="container">Law Study
  <input type="checkbox" name="subjects[]" value="law" {{ in_array('law',$subjects) ? 'checked' :'' }}>
  <span class="checkmark"></span>
</label>

@error('subjects')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Faculty:</strong><br>
  <input type="radio" id="science" name="faculty" value="science" {{ ($checkbox->faculty=='science') ? 'checked' :'' }}>
  <label for="science">SCIENCE</label><br>
  <input type="radio" id="management" name="faculty" value="management" {{ ($checkbox->faculty=='management') ? 'checked' :'' }}>
  <label for="management">MANAGEMENT</label><br>
  <input type="radio" id="law" name="faculty" value="law" {{ ($checkbox->faculty=='law') ? 'checked' :'' }}> 
  <label for="law">LAW</label>
@error('faculty')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<button type="ok" class="btn btn-primary ml-3">OK</button>
</div>
</form>
</div>
</body>
</html>

resources/views/checkboxes/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>checkbox</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
<style>
    .heading{
        color:black;
    }
    table tr th,table tr td{
        border:1px solid black !important;
        
    }
    table tr td{
        color:black;
        background-color: white;
    }
    </style>

</head>
<body>
<div class="container mt-2">
<div class="row">
<div class="col-lg-12 margin-tb">
<div class="pull-left">
<h2>Entrance Form</h2>
</div>
    <div class="row">
        <div class="pull-right mb-2 col-md-8">
            <a class="btn btn-success" href="{{ route('checkboxes.create') }}"> Create Checkbox</a>
        </div>
        <div class="col-md-4">
            <form action="" method="get">
                <input type="text" name="search" value="{{$search}}">
                <a class="btn btn-info" href="{{route('checkboxes.index')}}">Clear</a>
            </form>
        </div> 
    </div>
    <h4>Filters</h4>
    <form action="" method="GET">
            <div class="row">
            <div class="col-md-2">
                <label for="firstname">Firstname</label>
                <input type="text" name="first_name" value="{{$firstname}}">
            </div>
            <div class="col-md-2">
                <label for="lastname">Lastname</label>
                <input type="text" name="last_name" value="{{$lastname}}">
            </div>
            <div class="col-md-3">
                <button class="btn btn-primary" type="submit">Search</button>
            </div>
        </div>
        </form>
</div>
</div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
<p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered table-responsive table-striped" width="100%">
<tr>
<th class="heading">S.No</th>
<th class="heading">First Name</th>
<th class="heading">Last Name</th>
<th class="heading">Email</th>
<th class="heading" >Address</th>
<th class="heading">Contact Number</th>
<th class="heading">Subjects</th>
<th class="heading">Faculty</th>
<th class="heading" width="280px">Action</th>
</tr>
@foreach ($checkboxes as $checkbox)
<tr>
<td>{{ $loop->iteration }}</td>
<td>{{ $checkbox->firstname }}</td>
<td>{{ $checkbox->lastname }}</td>
<td>{{ $checkbox->email }}</td>
<td width="500px">{{ $checkbox->address }}</td>
<td>{{ $checkbox->contactnumber }}</td>
<td>{{ $checkbox->subjects }}</td>
<td>{{ $checkbox->faculty }}</td>
<td>
<form action="{{ route('checkboxes.destroy',$checkbox->id) }}" method="Post">
<a class="btn btn-primary" href="{{ route('checkboxes.edit',$checkbox->id) }}">Edit</a>
@csrf
@method('DELETE')
<button type="submit" class="btn btn-danger">Delete</button>
</form>
</td>
</tr>
@endforeach
</table>
</body>
</html>