routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CheckboxController;
use App\Http\Controllers\DepartmentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('companies', CompanyController::class);
Route::resource('departments', DepartmentController::class);
Route::resource('checkboxes', CheckboxController::class);

app/Models/Department.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory;
}

app/Http/Controllers/DepartmentController.php
<?php
namespace App\Http\Controllers;
use App\Models\Department;
use Illuminate\Http\Request;
class DepartmentController extends Controller
{
/**
* Display a listing of the resource.
*
* @return \Illuminate\Http\Response
*/
public function index()
{
$data['departments'] = Department::orderBy('id','desc')->paginate(5);
return view('departments.index', $data);
}
/**
* Show the form for creating a new resource.
*
* @return \Illuminate\Http\Response
*/
public function create()
{
return view('departments.create');
}
/**
* Store a newly created resource in storage.
*
* @param  \Illuminate\Http\Request  $request
* @return \Illuminate\Http\Response
*/
public function store(Request $request)
{
// $request->validate([
// 'department_name' => 'required',
// 'email' => 'required',
// 'number' => 'required',
// 'employeenumber' => 'required'
// ]);
$department = new department;
$department->department_name = $request->name;
$department->email = $request->email;
$department->number = $request->number;
$department->employeenumber = $request->employeenumber;
$department->save();
return redirect()->route('departments.index')
->with('success','Department has been created successfully.');
}
/**
* Display the specified resource.
*
* @param  \App\Department  $Department
* @return \Illuminate\Http\Response
*/
public function show(Department $department)
{
return view('departments.show',compact('department'));
} 
/**
* Show the form for editing the specified resource.
*
* @param  \App\Department  $Department
* @return \Illuminate\Http\Response
*/
public function edit(Department $department)
{
    
return view('departments.edit',compact('department'));

}
/**
* Update the specified resource in storage.
*
* @param  \Illuminate\Http\Request  $request
* @param  \App\Department  $Department
* @return \Illuminate\Http\Response
*/
public function update(Request $request, $id)
{
// $request->validate([
//     'department_name' => 'required',
//     'email' => 'required',
//     'number' => 'required',
//     'employeenumber' => 'required'
// ]);
$Department = Department::find($id);
$Department->department_name = $request->name;
$Department->email = $request->email;
$Department->number = $request->number;
$Department->employeenumber = $request->employeenumber;
$Department->save();
return redirect()->route('departments.index')
->with('success','Department Has Been updated successfully');
}
/**
* Remove the specified resource from storage.
*
* @param  \App\Department  $Department
* @return \Illuminate\Http\Response
*/
public function destroy(Department $department)
{
$department->delete();
return redirect()->route('departments.index')
->with('success','Department has been deleted successfully');
}
}

resources/views/departments/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Department</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
<div class="container mt-2">
<div class="row">
<div class="col-lg-12 margin-tb">
<div class="pull-left mb-2">
<h2>Add Department</h2>
</div>
<div class="pull-right">
<a class="btn btn-primary" href="{{ route('departments.index') }}"> Back</a>
</div>
</div>
</div>
@if(session('status'))
<div class="alert alert-success mb-1 mt-1">
{{ session('status') }}
</div>
@endif
<form action="{{ route('departments.store') }}" method="POST" enctype="multipart/form-data">
@csrf
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Name:</strong>
<input type="text" name="name" class="form-control" placeholder="Name">
@error('name')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Email:</strong>
<input type="email" name="email" class="form-control" placeholder="Email">
@error('email')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Number:</strong>
<input type="text" name="number" class="form-control" placeholder="Number">
@error('number')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Employee Number:</strong>
<input type="text" name="employeenumber" class="form-control" placeholder="Employee Number">
@error('employeenumber')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<button type="submit" class="btn btn-primary ml-3">Submit</button>
</div>
</form>
</body>
</html>

resources/views/departments/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Department</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
<div class="container mt-2">
<div class="row">
<div class="col-lg-12 margin-tb">
<div class="pull-left">
<h2>Edit Department</h2>
</div>
<div class="pull-right">
<a class="btn btn-primary" href="{{ route('departments.index') }}" enctype="multipart/form-data"> Back</a>
</div>
</div>
</div>
@if(session('status'))
<div class="alert alert-success mb-1 mt-1">
{{ session('status') }}
</div>
@endif
<form action="{{ route('departments.update',$department->id) }}" method="POST" enctype="multipart/form-data">
@csrf
@method('PUT')
<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Name:</strong>
<input type="text" name="name" value="{{ $department->department_name }}" class="form-control" placeholder="Name">
@error('name')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Email:</strong>
<input type="email" name="email" class="form-control" placeholder="Email" value="{{ $department->email }}">
@error('email')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Number:</strong>
<input type="text" name="number" value="{{ $department->number }}" class="form-control" placeholder="Number">
@error('number')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<div class="col-xs-12 col-sm-12 col-md-12">
<div class="form-group">
<strong>Employee Number:</strong>
<input type="text" name="employeenumber" value="{{ $department->employeenumber }}" class="form-control" placeholder="Employee Number">
@error('employeenumber')
<div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
@enderror
</div>
</div>
<button type="submit" class="btn btn-primary ml-3">Submit</button>
</div>
</form>
</div>
</body>
</html>

resources/views/departments/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Department</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" >
</head>
<body>
<div class="container mt-2">
<div class="row">
<div class="col-lg-12 margin-tb">
<div class="pull-left">
<h2>Department</h2>
</div>
<div class="pull-right mb-2">
<a class="btn btn-success" href="{{ route('departments.create') }}"> Create Department</a>
</div>
</div>
</div>
@if ($message = Session::get('success'))
<div class="alert alert-success">
<p>{{ $message }}</p>
</div>
@endif
<table class="table table-bordered">
<tr>
<th>S.No</th>
<th>Name</th>
<th>Email</th>
<th>Number</th>
<th>Employee Number</th>
<th width="280px">Action</th>
</tr>
@foreach ($departments as $Department)
<tr>
<td>{{ $Department->id }}</td>
<td>{{ $Department->department_name }}</td>
<td>{{ $Department->email }}</td>
<td>{{ $Department->number }}</td>
<td>{{ $Department->employeenumber }}</td>
<td>
<form action="{{ route('departments.destroy',$Department->id) }}" method="Post">
<a class="btn btn-primary" href="{{ route('departments.edit',$Department->id) }}">Edit</a>
@csrf
@method('DELETE')
<button type="submit" class="btn btn-danger">Delete</button>
</form>
</td>
</tr>
@endforeach
</table>
{!! $departments->links() !!}
</body>
</html>